name = "stm32_boards"
description = "stm32 boards code"
version = "1.0.0"
licenses = "BSD-3-Clause"

tags = ["embedded"]
website = "https://github.com/ohenley/stm32_boards"

authors = ["AdaCore"]
maintainers = ["olivier henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

[configuration.values]
[configuration.values.arm_cortex]
core = "m7f"

#[configuration.values.stm32_config]
#board = "stm32f746disco"
#mcu = "stm32f746x"
#runtime = "embedded"

[[depends-on]]
gnat_arm_elf = "^12"
stm32_config = "1.0.0"
arm_cortex = "1.0.0"
beta_types = "1.0.0"
hal_embedded = "1.0.0"
stm32_svd = "1.0.0"
stm32_drivers = "1.0.0"
stm32_components = "1.0.0"
